version: "3.8"

services:
  dbmysql01:
    container_name: mysql_devops
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    expose:
      - "33061"
    ports:
      - "33061:3306"
    volumes:
      - ./binds/mysql_01:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1G
